### ISSUE TITLE
EventEmitter for ClassLoader / Visitor Pattern

### ISSUE THREAD

**Issue by kylestev** [kylestev/jvm.js#32]
it could be incredibly beneficial for static analysis to analyze at parse time.

**Comment by kylestev** [comment]
I'm considering merging `kylestev/jvm-visitor` into master on this repo. The main benefit I see for merging visitors besides simplifying writing (a la ASM-style `ClassWriter`) would be exposing another mechanism for iterating jars and class files.

We could also potentially allow a `ClassVisitor` to be passed into `ClassLoader`/`Jar#unpack` for parsing/constructing the `ClassInfo` objects.

@TSedlar, thoughts?

**Comment by kylestev** [comment]
If I were to merge it, I think I'd move the deobfuscation classes out of the `jvm-visitor` repo and move them to their own `jvm-deob` package to keep things tidy in the core.

**Comment by TSedlar** [comment]
I think that'd be great and I do agree deobfuscation and similar future modules should be their own separate packages. (Other than possibly the framework/root class that is extended, for example, a 'DeobTransform' class.)

**Comment by kylestev** [comment]
Yeah that sounds good to me. I'm definitely planning on adding a Transform class.

**Comment by kylestev** [comment]
merged 04e98fecfc3
